# Generated by Django 4.2 on 2023-11-05 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=255)),
                ('car_year', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('miles_driven', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_photo', models.ImageField(blank=True, null=True, upload_to='car_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_start_date', models.DateField()),
                ('booking_end_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rentals.car')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
