# Generated by Django 4.2 on 2023-11-06 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rentals', '0002_car_pickup_latitude_car_pickup_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='pickup_latitude',
            field=models.DecimalField(decimal_places=6, default=19.4009, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='pickup_longitude',
            field=models.DecimalField(decimal_places=6, default=123.4738, max_digits=9),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('feedback', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
